module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Users', [
      {
        id: '206802',
        firstname: 'Martin',
        lastname: 'Scorsese',
        email: 'martin@amail.biz',
        password: '$2a$10$JrxOllv.pb7XF4NLE35CO.Zlt9/Fw9HZrQuErDnLCmnU0dqG/plZe',
        description: 'React, Node.js, Postgres, typescript',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        userPhoto: 'https://i1.sndcdn.com/artworks-000668037946-sxtf5b-t500x500.jpg',
      },
      {
        id: '537982',
        firstname: 'Артур',
        lastname: 'Пирожков',
        email: 'archie@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_KEvqvnEPoyufATZF3QinNk6oDCXMvVoVQg&usqp=CAU,',
      },
      {
        id: '589982',
        firstname: 'Артем',
        lastname: 'Коноплев',
        email: 'konoplev@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma45Yp9o',
        isActive: true,
        userPhoto: 'https://www.interfax.ru/ftproot/photos/photostory/2019/07/09/week4_700.jpg',
      },
      {
        id: '589983',
        firstname: 'Тарас',
        lastname: 'Бананов',
        email: 'Taras@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma45YpK9',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBOPC813VE7u05rBQXB-hZaiNrVBdi378glDlD8W8O6tW_D62Og4brzH48GrhQ26ij4JI&usqp=CAU',
      },
      {
        id: '589984',
        firstname: 'Карим',
        lastname: 'Курбанов',
        email: 'kur@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'Ma4123d-oK',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk2f03P_CydoVTsypLTSdNSHgbkyQqjIQZWQ&usqp=CAU',
      },
      {
        id: '589985',
        firstname: 'Егор',
        lastname: 'Летов',
        email: 'leto@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '898нгрsd',
        isActive: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdpwmXGes-oQyPp0_3QQaxBchbKOkNSuDZiQ&usqp=CAU',
      },
      {
        id: '589986',
        firstname: 'Иван',
        lastname: 'Жорин',
        email: 'jor@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'eRtgso0',
        isActive: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy31HCRF5dyJm7THnl-rjOoSPglQp1-OKo9Q&usqp=CAU',
      },
      {
        id: '589987',
        firstname: 'Ирина',
        lastname: 'Хакамада',
        email: 'haka@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: '2qVZQ5g23R',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_BWR2hctMuqIW_15x_uBLJ1y2R9JO-hQCCA&usqp=CAU',
      },
      {
        id: '58998',
        firstname: 'Михаил',
        lastname: 'Степанов',
        email: 'step@mail.ru',
        password: '$2a$10$bRmTM4D7S/awhB4G.1HYRe2LL99n7DqmcOHly/f3J1YRZSSnUdpEC',
        description: 'Proactive variability checker',
        isMentor: true,
        careerStart: '01.04.2020',
        companyId: 'eRtgsds0sdk',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_BWR2hctMuqIW_15x_uBLJ1y2R9JO-hQCCA&usqp=CAU',
      },
      {
        id: '145976',
        firstname: 'Clementine',
        lastname: 'Bauch',
        email: 'Nathan@yesenia.net',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJCTlLL7h7H3LpxCnyVpyg8EoDvbNHkFqrrw&usqp=CAU',

      },
      {
        id: '14597',
        firstname: 'Иван',
        lastname: 'Иванов',
        email: 'Nan@yesea.net',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCqaDf_PZap4h22_uQ4c9qDC__sb61AIXX4g&usqp=CAU',

      },
      {
        id: '14598',
        firstname: 'Перт',
        lastname: 'Петров',
        email: 'Petr@yesea.net',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7yLxef5eB183N5pPA27eipYx8WeKf9layyA&usqp=CAU',

      },
      {
        id: '14599',
        firstname: 'Жорик',
        lastname: 'Вартанов',
        email: 'Pertsd@yesea.net',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRki1P_x5Fad4u8XCzdEdsycXyCcwYTCZ9N8A&usqp=CAU',

      },
      {
        id: '145981',
        firstname: 'Алексей',
        lastname: 'Никитин',
        email: 'ggar@mail.ru',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaDAe985RZeJTGPUL4KJp7OYn-NewEQtfHvA&usqp=CAU',

      },
      {
        id: '145982',
        firstname: 'Херсон',
        lastname: 'Литвенежко',
        email: 'lit@mail.ru',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_XmUZZ4l_ArL9IJDUpHaXGQ-T0bLs_gfmng&usqp=CAU',

      },
      {
        id: '145983',
        firstname: 'Глеб',
        lastname: 'Аршавин',
        email: 'lfdt@mail.ru',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRABDC8UoE8RUEduze0q5vb4DvvPTSytT7eBQ&usqp=CAU',

      },
      {
        id: '145984',
        firstname: 'Марата',
        lastname: 'Раисова',
        email: 'rais@mail.ru',
        password: '$2a$10$0uOyE5mcB88GTuPglC.g6u79Otc/xuhxGpEF2LsSt6kj3rBlpXMHC',
        description: 'Face to face bifurcated interface',
        isMentor: false,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JroW6h0uubO0ps2cWhP7RzS9eV2LAgMpeQ&usqp=CAU',
      },
      {
        id: '365742',
        firstname: 'Patricia',
        lastname: 'Lebsack',
        email: 'Julianne.OConner@kory.org',
        password: '$2a$10$NHNDDmmhz/FXIBvZ4uXVNeT19Hl6VB01hQNSnFwx./EptJ79DSDSa',
        description: 'Multi-tiered zero tolerance productivity',
        isMentor: true,
        careerStart: '02.08.2014',
        companyId: 'ebDFCJ45OF',
        isActive: true,
        userPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpVHrfvYr_ecUzZNOnfWCeQScHq1hmo26lVw&usqp=CAU',
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
